version: '3.6'

services:
  database:
    build: ./setup_database
    container_name: postgres_raw_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=online_store
    volumes:
      - ./docker_volume:/docker_volume

  generator:
    build: ./data_generation
    container_name: data_generator
    environment:
      - POSTGRES_HOST=database
      - DATABASE=online_store
      - PSQL_USERNAME=postgres
      - PSQL_PASSWORD=postgres
      - BACKFILL_DAYS=1
      - VARIABLE_INSERT_DELAY_START=5
      - VARIABLE_INSERT_DELAY_STOP=10
    volumes:
      - ./docker_volume:/docker_volume
    depends_on:
      - database
