version: '3.6'

services:
  superset:
    build: .
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_FIRST_NAME=admin
      - ADMIN_LAST_NAME=user
      - ADMIN_EMAIL=admin@something.com
      - ADMIN_PWD=superset
