version: '3.6'

services:
  airflow:
    build: .
    container_name: airflow
    ports:
      - "8089:8089"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_FIRST_NAME=admin
      - ADMIN_LAST_NAME=user
      - ADMIN_EMAIL=admin@something.com
      - ADMIN_PWD=airflow
